services:

  eureka-server:
    build:
      context: ./  # Asumiendo que el Dockerfile está en la raíz de este repositorio
    ports:
      - "8762:8761"
    container_name: eureka-server
    networks:
      - backend-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - eureka.server.enable-self-preservation=false
      - eureka.server.eviction-interval-timer-in-ms=5000
      - eureka.server.renewal-strategy=true
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/  # URL para Docker

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Monta la configuración de Prometheus
    ports:
      - "9090:9090"  # Expón el puerto 9090
    networks:
      - backend-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - backend-network

networks:
  backend-network:
    external: true
