services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=P4ssword!
      - MYSQL_DATABASE=Backend_Wakanda_Salud
    ports:
      - "3306:3306"
    networks:
      - backend-network

  eureka-server:
    build:
      context: ./  # Asumiendo que el Dockerfile está en la raíz de este repositorio
    ports:
      - "8761:8761"
    container_name: eureka-server
    networks:
      - backend-network
    environment:
      - SPRING_PROFILES_ACTIVE=default  # Si usas algún perfil de configuración
      - eureka.server.enable-self-preservation=false
      - eureka.server.eviction-interval-timer-in-ms=5000
      - eureka.server.renewal-strategy=true

networks:
  backend-network:
    driver: bridge