global:
  scrape_interval: 15s  # Intervalo de recolección de métricas

scrape_configs:
  - job_name: "eureka-server"
    static_configs:
      - targets: ["eureka-server:8761"]  # Reemplaza con el nombre del contenedor y puerto
        labels:
          service: "eureka-server"
