global:
  scrape_interval: 15s  # Intervalo de recolección de métricas

scrape_configs:
  - job_name: "eureka-server"
    metrics_path: "/actuator/prometheus"  # Especifica el path de las métricas
    static_configs:
      - targets: ["eureka-server:8761"]  # Solo el hostname y el puerto
        labels:
          service: "eureka-server"

  - job_name: "backend-wakanda-salud"
    metrics_path: "/actuator/prometheus"  # Especifica el path de las métricas
    static_configs:
      - targets: ["backend-wakanda-salud:8090"]  # Solo el hostname y el puerto
        labels:
          service: "backend-wakanda-salud"

  - job_name: "backend-wakanda-agua"
    metrics_path: "/actuator/prometheus"  # Especifica el path de las métricas
    static_configs:
      - targets: [ "backend-wakanda-agua:8095" ]  # Solo el hostname y el puerto
        labels:
          service: "backend-wakanda-agua"